# -*- coding: utf-8 -*-
"""TCP_CLIENT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c-IpxkDa0DVErYH-6emLPae5CzUxdcU0
"""

import socket
target_host = "www.google.com"
target_port = 80
# create a socket object
client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
# connect the client
client.connect((target_host,target_port))
# send some data
client.send(b"GET / HTTP/1.1\r\nHost: google.com\r\n\r\n")
# receive some data
response = client.recv(4096)
print(response.decode())
client.close()